services:
  nodejs:
    # image: goal-api-docker
    image: caffeinets:latest
    container_name: caffeine-server
    restart: on-failure
    # env
    environment:
      - NODE_ENV=production
    # volumes:
    #   - /usr/src/app/node_modules
    build:
      context: .
      dockerfile: Dockerfile
      target: deploy
    # command: 'pnpm prod:cluster'
    ports:
      - 30000:30000
      - 30001:30001
    networks:
      - compose-network
networks:
  compose-network:
    driver: bridge
