version: '3.3'
services:
  mongo:
    image: mongo:5.0
    restart: always
    ports:
      - 27017:27017
    networks:
      - compose-network
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: username
    #   MONGO_INITDB_ROOT_PASSWORD: example
  redis:
    image: redis:6.2.4
    restart: always
    ports:
      - 6379:6379
    networks:
      - compose-network
  rabbitmq:
    image: rabbitmq:3.10-management
    restart: always
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    # volumes:
    #   - ~/.docker-config/rabbitmq/lib/:/var/lib/rabbitmq/
    #   - ~/.docker-config/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - compose-network
networks:
  compose-network:
    driver: bridge
