version: '3.3'
services:
  mongo:
    image: mongo:5.0
    restart: always
    ports:
      - 27017:27017
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: username
    #   MONGO_INITDB_ROOT_PASSWORD: example
  redis:
    image: redis:6.2.4
    restart: always
    ports:
      - 6379:6379
